project_id = "qupgqkvsrzpjgmycoliu"

[functions.generate-clinical-summary]
verify_jwt = false

[functions.chat-with-documents]
verify_jwt = false

[functions.generate-medical-letter]
verify_jwt = false